#!/usr/bin/env sh

aws --version
kubectl version

echo "----------"
export DOCKER_SERVER=$(aws sts get-caller-identity --query Account --output text).dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
export DOCKER_PASSWORD=`aws ecr get-login-password`
echo "Docker Registry: ${DOCKER_SERVER}"
echo "Docker Password: ${DOCKER_PASSWORD}"

echo "----------"
echo "Updating new secret for ECR..."
kubectl delete secret aws-registry || true
kubectl create secret docker-registry aws-registry --docker-username=AWS --docker-server=${DOCKER_SERVER} --docker-password=${DOCKER_PASSWORD} --docker-email=no
